# Generated by Django 4.2.11 on 2025-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
