# Generated by Django 5.0.1 on 2025-04-22 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_sessionstatus_groupsession_privatesession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Instructor Specialties",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="groupsession",
            name="price",
        ),
        migrations.RemoveField(
            model_name="groupsession",
            name="status_detail",
        ),
        migrations.RemoveField(
            model_name="privatesession",
            name="status_detail",
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="max_students",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("teaching_style", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="instructor_profiles/"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teaching_languages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="content_instructors",
                        to="content.language",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="instructors",
                        to="content.instructorspecialty",
                    ),
                ),
            ],
        ),
    ]
