# Generated by Django 5.0.1 on 2025-04-22 09:57

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0004_alter_groupsession_language_alter_groupsession_level_and_more",
        ),
        ("content", "0004_instructorspecialty_remove_groupsession_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="specialties",
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="teaching_languages",
        ),
        migrations.AlterField(
            model_name="privatesession",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resource",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="privatesession",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionattendance",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sessionattendance",
            name="session",
        ),
        migrations.RemoveField(
            model_name="sessionattendance",
            name="student",
        ),
        migrations.RemoveField(
            model_name="sessionreport",
            name="group_session",
        ),
        migrations.RemoveField(
            model_name="sessionreport",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="sessionreport",
            name="private_session",
        ),
        migrations.DeleteModel(
            name="SessionStatus",
        ),
        migrations.AlterModelOptions(
            name="groupsession",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AlterModelOptions(
            name="privatesession",
            options={"ordering": ["-start_time"]},
        ),
        migrations.RemoveConstraint(
            model_name="sessionfeedback",
            name="unique_private_session_feedback",
        ),
        migrations.RemoveConstraint(
            model_name="sessionfeedback",
            name="unique_group_session_feedback",
        ),
        migrations.RemoveField(
            model_name="groupsession",
            name="cancellation_by",
        ),
        migrations.RemoveField(
            model_name="groupsession",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="groupsession",
            name="completion_notes",
        ),
        migrations.RemoveField(
            model_name="privatesession",
            name="cancellation_by",
        ),
        migrations.RemoveField(
            model_name="privatesession",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="privatesession",
            name="completion_notes",
        ),
        migrations.AddField(
            model_name="groupsession",
            name="price",
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="instructor",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_sessions",
                to="content.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="tags",
            field=models.CharField(
                blank=True, default=1, help_text="Comma-separated tags", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="content.learningmodule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="privatesession",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_sessions",
                to="content.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="privatesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("available", "Available"),
                    ("booked", "Booked"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no-show", "No Show"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="content_resources/"
            ),
        ),
        migrations.AlterField(
            model_name="sessionfeedback",
            name="content_relevance",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 Stars"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionfeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 Stars"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="sessionfeedback",
            name="teaching_quality",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 Stars"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionfeedback",
            name="technical_quality",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 Stars"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instructorreview",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="content.instructor",
            ),
        ),
        migrations.AddField(
            model_name="instructorreview",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="InstructorSpecialty",
        ),
        migrations.AddField(
            model_name="instructor",
            name="specialties",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("business", "Business Language"),
                    ("academic", "Academic Language"),
                    ("conversation", "Conversation Practice"),
                    ("exam", "Exam Preparation"),
                    ("children", "Teaching Children"),
                    ("medical", "Medical Terminology"),
                    ("travel", "Travel & Tourism"),
                    ("technical", "Technical & Scientific"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="teaching_languages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="LanguageLevel",
        ),
        migrations.DeleteModel(
            name="SessionAttendance",
        ),
        migrations.DeleteModel(
            name="SessionReport",
        ),
        migrations.AlterUniqueTogether(
            name="instructorreview",
            unique_together={("instructor", "student")},
        ),
    ]
