# Generated by Django 5.0.1 on 2025-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_instructorreview_remove_instructor_specialties_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
