# Generated by Django 5.0.1 on 2025-04-22 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_instructorspecialty_groupsession_and_more"),
        ("content", "0004_instructorspecialty_remove_groupsession_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorspecialty",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                related_name="booking_instructors",
                to="booking.instructorspecialty",
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="teaching_languages",
            field=models.ManyToManyField(
                related_name="booking_instructors", to="content.language"
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_instructor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
