# Generated by Django 5.0.1 on 2025-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_instructorspecialty_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupsession",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                max_length=2,
            ),
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="teaching_languages",
        ),
        migrations.AlterField(
            model_name="privatesessionslot",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("sw", "Swahili"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="privatesessionslot",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper Intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficient"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="teaching_languages",
            field=models.CharField(
                blank=True, help_text="Comma-separated language codes", max_length=100
            ),
        ),
    ]
