# Generated by Django 4.2.11 on 2025-05-08 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Meeting notes or agenda", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="recording_url",
            field=models.URLField(
                blank=True, help_text="URL to recorded session if available", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["start_time"], name="meetings_me_start_t_7a37c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["status"], name="meetings_me_status_14fbb6_idx"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["teacher"], name="meetings_me_teacher_ce548f_idx"
            ),
        ),
    ]
