# Generated by Django 4.2.11 on 2025-05-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
